functionsDirectory = "C:\\Users\\barca2\\.gemini\\antigravity\\playground\\luminescent-ionosphere\\netlify\\functions"
functionsDirectoryOrigin = "default"
headers = []
redirects = []

[build]
publish = "C:\\Users\\barca2\\.gemini\\antigravity\\playground\\luminescent-ionosphere\\.next"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"
functions = "C:\\Users\\barca2\\.gemini\\antigravity\\playground\\luminescent-ionosphere\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
included_files = ["node_modules/.prisma/**/*", "node_modules/@prisma/**/*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"
pinned_version = "5"

[plugins.inputs]