import { NextResponse } from 'next/server'
import Facturapi from 'facturapi'
import prisma from '../../../../../lib/prisma'

export async function GET(request, { params }) {
  const { id } = await params
  const { searchParams } = new URL(request.url)
  const format = searchParams.get('type') || 'pdf' // 'pdf' or 'xml'
  
  if (!['pdf', 'xml', 'zip'].includes(format)) {
    return NextResponse.json({ error: 'Formato inválido. Use pdf, xml o zip' }, { status: 400 })
  }

  try {
    const fac = await prisma.factura.findUnique({
      where: { uuid: id },
      include: { empresa: true }
    });

    if (!fac || !fac.uuid) {
      return NextResponse.json({ error: 'Factura no encontrada o no timbrada' }, { status: 404 })
    }

    let targetKey = fac.empresa.facturapiLiveKey || process.env.FACTURAPI_LIVE_KEY;
    if (fac.estatus && fac.estatus.includes('Test Fallback')) {
      targetKey = fac.empresa.facturapiTestKey || process.env.FACTURAPI_TEST_KEY || process.env.FACTURAPI_LIVE_KEY;
    } else if (!fac.empresa.cerPath) {
      targetKey = fac.empresa.facturapiTestKey || process.env.FACTURAPI_TEST_KEY || process.env.FACTURAPI_LIVE_KEY;
    }

    if (!targetKey || targetKey.includes('PENDING_KEY')) {
      return NextResponse.json({ error: 'LLave Facturapi no configurada para la empresa' }, { status: 500 })
    }

    const tenantFacturapi = new Facturapi(targetKey);

    let stream;
    let contentType;
    let fileName = `Factura_${fac.uuid}`;
    let webStream;
    
    // If the invoice was generated via Facturapi, it has a facturapiId
    if (fac.facturapiId) {
      if (format === 'pdf') {
        stream = await tenantFacturapi.invoices.downloadPdf(fac.facturapiId);
        contentType = 'application/pdf';
        fileName += '.pdf';
      } else if (format === 'xml') {
        stream = await tenantFacturapi.invoices.downloadXml(fac.facturapiId);
        contentType = 'application/xml';
        fileName += '.xml';
      } else if (format === 'zip') {
        stream = await tenantFacturapi.invoices.downloadZip(fac.facturapiId);
        contentType = 'application/zip';
        fileName += '.zip';
      }
      
      const { Readable } = require('stream');
      webStream = Readable.toWeb(stream);
      
    } else {
      // The invoice was synced from SAT and not generated by Facturapi
      if (format === 'xml') {
        if (!fac.xmlBase64 && !fac.xmlUrl) {
           return NextResponse.json({ error: 'XML no disponible para esta factura importada del SAT' }, { status: 404 });
        }
        
        let xmlContent = '';
        if (fac.xmlBase64) {
           xmlContent = Buffer.from(fac.xmlBase64, 'base64').toString('utf-8');
        } else {
           // Si usaramos xmlUrl, tendríamos que descargarlo primero, por ahora asumimos que xmlBase64 tiene la data
           return NextResponse.json({ error: 'El archivo debe ser descargado desde la URL externa' }, { status: 400 });
        }
        
        contentType = 'application/xml';
        fileName += '.xml';
        const encoder = new TextEncoder();
        webStream = new ReadableStream({
          start(controller) {
            controller.enqueue(encoder.encode(xmlContent));
            controller.close();
          }
        });
      } else {
        return NextResponse.json({ error: 'No es posible descargar el PDF de facturas importadas del SAT automáticamente por ahora. Sube el PDF manualmente.' }, { status: 400 });
      }
    }

    return new Response(webStream, {
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': `attachment; filename="${fileName}"`
      }
    });

  } catch (error) {
    console.error(`Error descargando comprobante ${id}:`, error);
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}
