import { NextResponse } from 'next/server'
import facturapi from '../../../../../lib/facturapi'
import prisma from '../../../../../lib/prisma'

export async function GET(request, { params }) {
  const { id } = await params
  const { searchParams } = new URL(request.url)
  const format = searchParams.get('type') || 'pdf' // 'pdf' or 'xml'
  
  if (!['pdf', 'xml', 'zip'].includes(format)) {
    return NextResponse.json({ error: 'Formato inválido. Use pdf, xml o zip' }, { status: 400 })
  }

  try {
    const fac = await prisma.factura.findUnique({
      where: { uuid: id },
      include: { empresa: true }
    });

    if (!fac || !fac.uuid) {
      return NextResponse.json({ error: 'Factura no encontrada o no timbrada' }, { status: 404 })
    }

    let targetKey = fac.empresa.facturapiLiveKey || process.env.FACTURAPI_LIVE_KEY;
    if (fac.estatus && fac.estatus.includes('Test Fallback')) {
      targetKey = fac.empresa.facturapiTestKey || process.env.FACTURAPI_TEST_KEY || process.env.FACTURAPI_LIVE_KEY;
    }

    if (!targetKey || targetKey.includes('PENDING_KEY')) {
      return NextResponse.json({ error: 'LLave Facturapi no configurada para la empresa' }, { status: 500 })
    }

    const tenantFacturapi = new facturapi.constructor(targetKey);

    let stream;
    let contentType;
    let fileName = `Factura_${fac.uuid}`;
    let webStream;
    
    // Si la factura fue generada por Facturapi, su uuid local es el ID interno de Facturapi (ej. inv_xyz)
    // Los UUIDs del SAT reales tienen 36 caracteres.
    const isFacturapi = fac.uuid && fac.uuid.length !== 36 && !fac.uuid.startsWith('sim_uuid');
    
    if (isFacturapi) {
      if (format === 'pdf') {
        stream = await tenantFacturapi.invoices.downloadPdf(fac.uuid);
        contentType = 'application/pdf';
        fileName += '.pdf';
      } else if (format === 'xml') {
        stream = await tenantFacturapi.invoices.downloadXml(fac.uuid);
        contentType = 'application/xml';
        fileName += '.xml';
      } else if (format === 'zip') {
        stream = await tenantFacturapi.invoices.downloadZip(fac.uuid);
        contentType = 'application/zip';
        fileName += '.zip';
      }
      
      const { Readable } = require('stream');
      webStream = Readable.toWeb(stream);
      
    } else {
      // The invoice was synced from SAT and not generated by Facturapi
      if (format === 'xml') {
        if (!fac.xmlBase64 && !fac.xmlUrl) {
          const htmlMsg = `
            <html>
              <head><title>XML no disponible</title></head>
              <body style="font-family: Arial, sans-serif; padding: 40px; text-align: center; background-color: #0f172a; color: #f8fafc;">
                <div style="background: #1e293b; max-width: 600px; margin: 0 auto; padding: 30px; border-radius: 8px; border: 1px solid #334155; box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.5);">
                  <h2 style="color: #facc15; margin-top: 0;">XML No Disponible</h2>
                  <p style="font-size: 1.1rem; line-height: 1.5;">El archivo XML de esta factura aún no ha sido descargado o procesado.</p>
                  <button onclick="window.close()" style="padding: 10px 24px; background: #ca8a04; color: white; border: none; border-radius: 6px; cursor: pointer; font-size: 1rem; font-weight: bold;">Cerrar Pestaña</button>
                </div>
              </body>
            </html>
          `;
          return new Response(htmlMsg, { status: 404, headers: { 'Content-Type': 'text/html; charset=utf-8' } });
        }
        
        let xmlContent = '';
        if (fac.xmlBase64) {
           xmlContent = Buffer.from(fac.xmlBase64, 'base64').toString('utf-8');
        } else {
          const htmlMsg = `
            <html>
              <head><title>XML externo</title></head>
              <body style="font-family: Arial, sans-serif; padding: 40px; text-align: center; background-color: #0f172a; color: #f8fafc;">
                <div style="background: #1e293b; max-width: 600px; margin: 0 auto; padding: 30px; border-radius: 8px; border: 1px solid #334155;">
                  <h2 style="color: #facc15;">Archivo Externo</h2>
                  <p>El archivo debe ser descargado desde una URL externa.</p>
                  <button onclick="window.close()" style="padding: 10px 24px; background: #ca8a04; color: white; border: none; border-radius: 6px; cursor: pointer;">Cerrar Pestaña</button>
                </div>
              </body>
            </html>
          `;
          return new Response(htmlMsg, { status: 400, headers: { 'Content-Type': 'text/html; charset=utf-8' } });
        }
        
        contentType = 'application/xml';
        fileName += '.xml';
        const encoder = new TextEncoder();
        webStream = new ReadableStream({
          start(controller) {
            controller.enqueue(encoder.encode(xmlContent));
            controller.close();
          }
        });
      } else {
        if (format === 'pdf' && fac.pdfBase64) {
          let pdfContent = Buffer.from(fac.pdfBase64, 'base64');
          contentType = 'application/pdf';
          fileName += '.pdf';
          webStream = new ReadableStream({
            start(controller) {
              controller.enqueue(pdfContent);
              controller.close();
            }
          });
        } else {
          const htmlMsg = `
            <html>
              <head><title>PDF no disponible</title></head>
              <body style="font-family: Arial, sans-serif; padding: 40px; text-align: center; background-color: #0f172a; color: #f8fafc;">
                <div style="background: #1e293b; max-width: 600px; margin: 0 auto; padding: 30px; border-radius: 8px; border: 1px solid #334155; box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.5);">
                  <h2 style="color: #38bdf8; margin-top: 0;">Representación Gráfica No Disponible</h2>
                  <p style="font-size: 1.1rem; line-height: 1.5;">Este comprobante fue importado masivamente desde el SAT en formato XML, el cual es el único documento oficial.</p>
                  <p style="font-size: 1rem; color: #94a3b8; margin-bottom: 30px;">Para poder visualizar el PDF aquí, debes adjuntarlo primero usando la opción <strong>"Subir PDF"</strong> en la tabla de facturas.</p>
                  <button onclick="window.close()" style="padding: 10px 24px; background: #0284c7; color: white; border: none; border-radius: 6px; cursor: pointer; font-size: 1rem; font-weight: bold;">Cerrar Pestaña</button>
                </div>
              </body>
            </html>
          `;
          return new Response(htmlMsg, { status: 404, headers: { 'Content-Type': 'text/html; charset=utf-8' } });
        }
      }
    }

    return new Response(webStream, {
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': `attachment; filename="${fileName}"`
      }
    });

  } catch (error) {
    console.error(`Error descargando comprobante ${id}:`, error);
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}
